# Generated by Django 5.0.4 on 2024-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address of Venue')),
                ('pincode', models.IntegerField(verbose_name='Pincode')),
                ('phone_no', models.IntegerField(verbose_name='Contact Number')),
                ('website', models.CharField(max_length=100, verbose_name='Website Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
